config/routes.rb
Rails.application.routes.draw do
  resources :zones
  resources :people
  put '/people/:id/enter', to: 'people#enter'
  put '/people/:id/exit', to: 'people#exit'
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/zone.rb
class Zone < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
end

app/controllers/people_controller.rb
require 'time'

class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  def get_current_from_api(machine_id)
    url = "https://#{Settings.machine.user}:#{Settings.machine.password}@#{Settings.machine.url_base}/equipments/#{machine_id}/"
    response = RestClient.get url
    return JSON.parse(response.body)
  end

  def get_current_temperature
    c = @zone.previous_temperature
    return @zone.target_temperature if c.nil?

    diff_sec = Time.now - @zone.previous_temperature_update
    return @zone.target_temperature if diff_sec > TIME_DIFF

    temp_diff = @zone.target_temperature - @zone.previous_temperature

    puts temp_diff

    return c + (temp_diff * diff_sec / TIME_DIFF)

  end

  def get_comfortable_temperature(people, current_temperature)
    temperatures = people.map {|person| person.comfortable_temperature }
    average = people.blank? ? current_temperature : temperatures.inject(0.0){|r,i| r+=i }/temperatures.size
    average = current_temperature if average.nil?
    average = 20 if average < 20
    average = 30 if average > 30
    average = average.to_i
  end

  def set_target_temperature(target_temperature, machine_id)
    params = {"id": machine_id,
      "status": {
        "power": 1,
        "operation_mode": 4,
        "set_temperature": target_temperature,
        "fan_speed": 2,
        "fan_direction": 7
      }
    }
    url = "https://#{Settings.machine.user}:#{Settings.machine.password}@#{Settings.machine.url_base}/equipments/#{machine_id}/"
    response = RestClient.post url, params.to_json, {content_type: :json, accept: :json}
    return JSON.parse(response.body)
  end

  def enter
    args = JSON.parse(request.body.read)
    zone_id = args['zone_id']
    @person = Person.find(params[:id])
    @person.zone_id = zone_id
    @person.save

    # response zone he entered
    @zone = Zone.find(zone_id)
    @people = Person.where(zone_id: @zone.id)

#    current_machine = get_current(@zone.machine_id)
#    current_temperature = current_machine['status']['room_temperature']
    current_temperature = get_current_temperature
    @zone.target_temperature = get_comfortable_temperature(@people, current_temperature)

    @zone.previous_temperature = current_temperature
    @zone.previous_temperature_update = Time.now
    @zone.save

    set_target_temperature(@zone.target_temperature, @zone.machine_id)

    render 'zones/show'
  end
  def exit
    @person = Person.find(params[:id])
    zone_id_left = @person.zone_id

    @person.zone_id = nil
    @person.save

    # error handling

    # response zone he left
    begin
      @zone = Zone.find(zone_id_left)
    rescue
      render json: {}, status: '404'
      return
    end
    @people = Person.where(zone_id: @zone.id)

#    current_machine = get_current(@zone.machine_id)
#    current_temperature = current_machine['status']['room_temperature']
    current_temperature = get_current_temperature
    @zone.target_temperature = get_comfortable_temperature(@people, current_temperature)

    @zone.previous_temperature = current_temperature
    @zone.previous_temperature_update = Time.now
    @zone.save

    set_target_temperature(@zone.target_temperature, @zone.machine_id)

    render 'zones/show'
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :image_name, :gender, :temperature_preference, :comfortable_temperature, :comfortable_humidity, :zone_id)
    end
end

app/controllers/zones_controller.rb
require 'time'

TIME_DIFF = 25

class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]

  def get_current_from_api(machine_id)
    url = "https://#{Settings.machine.user}:#{Settings.machine.password}@#{Settings.machine.url_base}/equipments/#{machine_id}/"
    response = RestClient.get url
    return JSON.parse(response.body)
  end

  def get_current_temperature
    c = @zone.previous_temperature
    return @zone.target_temperature if c.nil?

    diff_sec = Time.now - @zone.previous_temperature_update
    return @zone.target_temperature if diff_sec > TIME_DIFF

    temp_diff = @zone.target_temperature - @zone.previous_temperature

    puts temp_diff

    return c + (temp_diff * diff_sec / TIME_DIFF)

  end

  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
    @people = Person.where(zone_id: @zone.id)
    @people = [] if @people.nil?
#    current_machine = get_current(@zone.machine_id)
#    current_temperature = current_machine['status']['room_temperature']
    @zone.current_temperature = get_current_temperature
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create
    @zone = Zone.new(zone_params)

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to zones_url, notice: 'Zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:zone_name, :target_temperature, :current_temperature, :machine_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackathon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_name %><br>
    <%= f.text_field :image_name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.number_field :gender %>
  </div>
  <div class="field">
    <%= f.label :temperature_preference %><br>
    <%= f.text_field :temperature_preference %>
  </div>
  <div class="field">
    <%= f.label :comfortable_temperature %><br>
    <%= f.text_field :comfortable_temperature %>
  </div>
  <div class="field">
    <%= f.label :comfortable_humidity %><br>
    <%= f.text_field :comfortable_humidity %>
  </div>
  <div class="field">
    <%= f.label :zone_id %><br>
    <%= f.text_field :zone_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image name</th>
      <th>Gender</th>
      <th>Temperature preference</th>
      <th>Comfortable temperature</th>
      <th>Comfortable humidity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.image_name %></td>
        <td><%= person.gender %></td>
        <td><%= person.temperature_preference %></td>
        <td><%= person.comfortable_temperature %></td>
        <td><%= person.comfortable_humidity %></td>
        <td><%= person.zone_id %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Image name:</strong>
  <%= @person.image_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @person.gender %>
</p>

<p>
  <strong>Temperature preference:</strong>
  <%= @person.temperature_preference %>
</p>

<p>
  <strong>Comfortable temperature:</strong>
  <%= @person.comfortable_temperature %>
</p>

<p>
  <strong>Comfortable humidity:</strong>
  <%= @person.comfortable_humidity %>
</p>
<p>
  <strong>Zone ID:</strong>
  <%= @person.zone_id %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/zones/_form.html.erb
<%= form_for(@zone) do |f| %>
  <% if @zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
      <% @zone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zone_name %><br>
    <%= f.text_field :zone_name %>
  </div>
  <div class="field">
    <%= f.label :target_temperature %><br>
    <%= f.text_field :target_temperature %>
  </div>
  <div class="field">
    <%= f.label :current_temperature %><br>
    <%= f.text_field :current_temperature %>
  </div>
  <div class="field">
    <%= f.label :machine_id %><br>
    <%= f.text_field :machine_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zones/edit.html.erb
<h1>Editing Zone</h1>

<%= render 'form' %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Zones</h1>

<table>
  <thead>
    <tr>
      <th>Zone name</th>
      <th>Target temperature</th>
      <th>Current temperature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zones.each do |zone| %>
      <tr>
        <td><%= zone.zone_name %></td>
        <td><%= zone.target_temperature %></td>
        <td><%= zone.current_temperature %></td>
        <td><%= zone.machine_id %></td>
        <td><%= link_to 'Show', zone %></td>
        <td><%= link_to 'Edit', edit_zone_path(zone) %></td>
        <td><%= link_to 'Destroy', zone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zone', new_zone_path %>

app/views/zones/new.html.erb
<h1>New Zone</h1>

<%= render 'form' %>

<%= link_to 'Back', zones_path %>

app/views/zones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zone name:</strong>
  <%= @zone.zone_name %>
</p>

<p>
  <strong>Target temperature:</strong>
  <%= @zone.target_temperature %>
</p>

<p>
  <strong>Current temperature:</strong>
  <%= @zone.current_temperature %>
</p>
<p>
  <strong>Machine ID:</strong>
  <%= @zone.machine_id %>
</p>

<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>